version: "3.8"
services:
  authservice:
    container_name: authservice
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/homework.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    restart: on-failure
    
  imageservice:
    container_name: imageservice
    ports:
      - "8010:80"
      - "8011:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/homework.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: ImageService/Dockerfile
    restart: on-failure